/* Auto-generated by genmsg_cpp for file /home/diro/ros_workspace/final_project/trunk/manipulation_transforms/srv/MapObjectTwistToEffectors.srv */
#ifndef MANIPULATION_TRANSFORMS_SERVICE_MAPOBJECTTWISTTOEFFECTORS_H
#define MANIPULATION_TRANSFORMS_SERVICE_MAPOBJECTTWISTTOEFFECTORS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "geometry_msgs/TwistStamped.h"


#include "geometry_msgs/TwistStamped.h"

namespace manipulation_transforms
{
template <class ContainerAllocator>
struct MapObjectTwistToEffectorsRequest_ {
  typedef MapObjectTwistToEffectorsRequest_<ContainerAllocator> Type;

  MapObjectTwistToEffectorsRequest_()
  : object_twist()
  {
  }

  MapObjectTwistToEffectorsRequest_(const ContainerAllocator& _alloc)
  : object_twist(_alloc)
  {
  }

  typedef  ::geometry_msgs::TwistStamped_<ContainerAllocator>  _object_twist_type;
   ::geometry_msgs::TwistStamped_<ContainerAllocator>  object_twist;


  typedef boost::shared_ptr< ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MapObjectTwistToEffectorsRequest
typedef  ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<std::allocator<void> > MapObjectTwistToEffectorsRequest;

typedef boost::shared_ptr< ::manipulation_transforms::MapObjectTwistToEffectorsRequest> MapObjectTwistToEffectorsRequestPtr;
typedef boost::shared_ptr< ::manipulation_transforms::MapObjectTwistToEffectorsRequest const> MapObjectTwistToEffectorsRequestConstPtr;


template <class ContainerAllocator>
struct MapObjectTwistToEffectorsResponse_ {
  typedef MapObjectTwistToEffectorsResponse_<ContainerAllocator> Type;

  MapObjectTwistToEffectorsResponse_()
  : effector_twists()
  {
  }

  MapObjectTwistToEffectorsResponse_(const ContainerAllocator& _alloc)
  : effector_twists(_alloc)
  {
  }

  typedef std::vector< ::geometry_msgs::TwistStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::TwistStamped_<ContainerAllocator> >::other >  _effector_twists_type;
  std::vector< ::geometry_msgs::TwistStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::TwistStamped_<ContainerAllocator> >::other >  effector_twists;


  typedef boost::shared_ptr< ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MapObjectTwistToEffectorsResponse
typedef  ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<std::allocator<void> > MapObjectTwistToEffectorsResponse;

typedef boost::shared_ptr< ::manipulation_transforms::MapObjectTwistToEffectorsResponse> MapObjectTwistToEffectorsResponsePtr;
typedef boost::shared_ptr< ::manipulation_transforms::MapObjectTwistToEffectorsResponse const> MapObjectTwistToEffectorsResponseConstPtr;

struct MapObjectTwistToEffectors
{

typedef MapObjectTwistToEffectorsRequest Request;
typedef MapObjectTwistToEffectorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct MapObjectTwistToEffectors
} // namespace manipulation_transforms

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "520cb950a1ab872cff62b14155b5a20c";
  }

  static const char* value(const  ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x520cb950a1ab872cULL;
  static const uint64_t static_value2 = 0xff62b14155b5a20cULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manipulation_transforms/MapObjectTwistToEffectorsRequest";
  }

  static const char* value(const  ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
geometry_msgs/TwistStamped object_twist\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistStamped\n\
# A twist with reference coordinate frame and timestamp\n\
Header header\n\
Twist twist\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into it's linear and angular parts. \n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9e6592ec3797ef41e0f2bd288e07c910";
  }

  static const char* value(const  ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9e6592ec3797ef41ULL;
  static const uint64_t static_value2 = 0xe0f2bd288e07c910ULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manipulation_transforms/MapObjectTwistToEffectorsResponse";
  }

  static const char* value(const  ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
geometry_msgs/TwistStamped[] effector_twists\n\
\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistStamped\n\
# A twist with reference coordinate frame and timestamp\n\
Header header\n\
Twist twist\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into it's linear and angular parts. \n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.object_twist);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MapObjectTwistToEffectorsRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.effector_twists);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MapObjectTwistToEffectorsResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<manipulation_transforms::MapObjectTwistToEffectors> {
  static const char* value() 
  {
    return "1bb5479e5565270d07bd4dd38bdd26c9";
  }

  static const char* value(const manipulation_transforms::MapObjectTwistToEffectors&) { return value(); } 
};

template<>
struct DataType<manipulation_transforms::MapObjectTwistToEffectors> {
  static const char* value() 
  {
    return "manipulation_transforms/MapObjectTwistToEffectors";
  }

  static const char* value(const manipulation_transforms::MapObjectTwistToEffectors&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1bb5479e5565270d07bd4dd38bdd26c9";
  }

  static const char* value(const manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manipulation_transforms/MapObjectTwistToEffectors";
  }

  static const char* value(const manipulation_transforms::MapObjectTwistToEffectorsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1bb5479e5565270d07bd4dd38bdd26c9";
  }

  static const char* value(const manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manipulation_transforms/MapObjectTwistToEffectors";
  }

  static const char* value(const manipulation_transforms::MapObjectTwistToEffectorsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATION_TRANSFORMS_SERVICE_MAPOBJECTTWISTTOEFFECTORS_H

