/* Auto-generated by genmsg_cpp for file /home/diro/ros_workspace/final_project/trunk/cart_pushing_msgs/msg/RobotCartPath.msg */
#ifndef CART_PUSHING_MSGS_MESSAGE_ROBOTCARTPATH_H
#define CART_PUSHING_MSGS_MESSAGE_ROBOTCARTPATH_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "cart_pushing_msgs/RobotCartConfiguration.h"

namespace cart_pushing_msgs
{
template <class ContainerAllocator>
struct RobotCartPath_ {
  typedef RobotCartPath_<ContainerAllocator> Type;

  RobotCartPath_()
  : header()
  , path()
  {
  }

  RobotCartPath_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , path(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::cart_pushing_msgs::RobotCartConfiguration_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cart_pushing_msgs::RobotCartConfiguration_<ContainerAllocator> >::other >  _path_type;
  std::vector< ::cart_pushing_msgs::RobotCartConfiguration_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cart_pushing_msgs::RobotCartConfiguration_<ContainerAllocator> >::other >  path;


  typedef boost::shared_ptr< ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RobotCartPath
typedef  ::cart_pushing_msgs::RobotCartPath_<std::allocator<void> > RobotCartPath;

typedef boost::shared_ptr< ::cart_pushing_msgs::RobotCartPath> RobotCartPathPtr;
typedef boost::shared_ptr< ::cart_pushing_msgs::RobotCartPath const> RobotCartPathConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cart_pushing_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ab8354991dcdaddeaed1d1d8e653e14c";
  }

  static const char* value(const  ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xab8354991dcdaddeULL;
  static const uint64_t static_value2 = 0xaed1d1d8e653e14cULL;
};

template<class ContainerAllocator>
struct DataType< ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cart_pushing_msgs/RobotCartPath";
  }

  static const char* value(const  ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
RobotCartConfiguration[] path\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cart_pushing_msgs/RobotCartConfiguration\n\
# Robot's pose in reference frame\n\
geometry_msgs/Pose robot_pose\n\
\n\
# Cart's pose in base frame\n\
geometry_msgs/Pose cart_pose\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.path);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RobotCartPath_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cart_pushing_msgs::RobotCartPath_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cart_pushing_msgs::RobotCartConfiguration_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CART_PUSHING_MSGS_MESSAGE_ROBOTCARTPATH_H

